### ISSUE TITLE
Adopt the Kite Oozie URI Handler

### ISSUE THREAD

**Issue by rbrush** [rbrush/kite-apps#1]
The current implementation doesn’t take advantage of Kite URIs in Oozie, and follows an unsafe workaround of checking for the presence of partitions in HDFS. This is an abstraction leak and could break at any time.

**Comment by rdblue** [comment]
> This is an abstraction leak and could break at any time.

Yep. I plan to.

**Comment by rbrush** [comment]
Actually, this shouldn't be an issue any longer as of the above commit. All code goes through the KiteURIHandler released in Kite 1.1. I'm going to go ahead and close this one, but we can reopen or create a new issue if I'm missing something.

**Comment by rdblue** [comment]
I meant that I plan to break the assumptions about partition layout in HDFS. :)
