### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by rdblue** [rbrush/kite-apps#11]
I just looked through the repo and didn't notice any license headers or a LICENSE file (nor a NOTICE with attribution for code included from other sources). It just gets harder to add that stuff later, so I recommend getting it done soon.

**Comment by rbrush** [comment]
Will do. Would it make things easier moving forward if I reassigned copyright to Cloudera? Right now it technically should be under Cerner's copyright (but an Apache license), but if we view this as a pending contribution to Kite we can reassign it.

Eventually we'd like to see this land as an Apache project outright, but we can work that out when the time is right.

**Comment by rdblue** [comment]
I don't think it would be a good idea to assign the copyright to Cloudera. That should be done with a software grant agreement like you use to contribute a large codebase to Apache, which means we probably don't want to do the work twice if we can avoid it.

I think the main thing is just to state who owns the copyright currently and under what license people can use the software. It looks like you might have grabbed some code from elsewhere, too (at least, I recognize the [CLI Main](https://github.com/rbrush/kite-apps/blob/master/kite-apps-cli/src/main/java/org/kitesdk/apps/cli/Main.java)). So if you remember where those cases are, I recommend putting in a header for all copyright holders.

**Comment by rbrush** [comment]
Yeah, the CLI main (and a couple other places like the shell script to launch it) are from Kite proper, with the intention that they would be merged together. My oversight for not properly attributing it and I'll add it.

**Comment by rbrush** [comment]
I think this is taken care of with the above commit, which includes licenses in each file, appropriate NOTICE.txt and LICENSE.txt files, and the Apache Rat plugin to validate things.

@rdblue, if you saw anything I missed please let me know. Otherwise I'll plan on just merging this into master soon.

**Comment by rbrush** [comment]
Let's try that again...the latest commit includes an oversight from the first one.

**Comment by rbrush** [comment]
I've incorporated @rdblue's suggestions, squashed the updates, and merged them into master. I'm going to go ahead and close this; we can reopen or create a new issue if I missed something.
