### ISSUE TITLE
Schedule of input datasets is inferred in an unreliable fashion

### ISSUE THREAD

**Issue by ben-roling** [rbrush/kite-apps#5]
The Schedule.Builder.withView() method lacks sufficient information to know the schedule of input datasets.

The method takes a URI pattern and frequency as argument but this is only a partial definition of a dataset.  Another key element of the dataset definition is the "initial-instance", which sets the anchor point for the frequency.

OozieScheduling hardcodes the initial-instance on datasets to `new Instant()`, which expects the input dataset will have a schedule that at least aligns in such a way that the real schedule and the perceived schedule align.

For example, if the input dataset has a schedule of every 2 minutes starting at 00:00 and the OozieScheduling.writeCoordinatorDatasets() method is invoked when the minute is 00:01 then it is going to incorrectly expect instances at 00:01, 00:03, 00:05, etc which will never line up with the actual instances that occur at 00:00, 00:02, 00:04, etc.

The TriggeredApp example in kite-apps-examples uses a frequency of every 1 minute so the issue is not exposed.  With the frequency set to every 2 minutes for both DataGeneratorApp and TriggeredApp you could get by without seeing the issue by deploying both apps in either an odd minute or an even minute but if you deployed one on a even minute and the other on an odd minute you should see the problem.

Something else you may notice is that the coordinator nominal time schedule and the output dataset nominal time schedule may not match as the start time of the coordinator and the initial-instance may not be set to the same value.  For example, an every 2 minute coordinator may start on an even minute but the dataset declaration has initial-instance on the odd minute.  This itself is not exactly a problem but it is distracting.

**Comment by rbrush** [comment]
I'm thinking of fixing this by:
1. Overloading withView so users can specify at least a start instant if desired.
2. Make the default behavior (using the purity withView arity) to align with the top of the hour. So if I submit a 5-minute frequency at 00:04, its initial instance will be 00:05, aligning it with the hour. (Technically we'd align it with the top of the next hour, since frequencies that don't match an hour.) I think this aligns with most usage patterns and keeps the simple case simple.

We could go even further and offer an overloaded withView that simply infers its frequency from the schedule of the job. So a job with "0 \* \* \* _" would have a 60-minute frequency at the top of the hour. "_/5 \* \* \* *" would have a 5-minute frequency, etc.

**Comment by ben-roling** [comment]
What you suggest could work in some cases of assuming alignment with the top of the hour but there is still the question of alignment with the top of what hour?  For example, if you did withView("myinput", EVENT_URI_PATTERN, 7), then what are the instances of the dataset?  They align with the top of what hour?  You would have to make the assumption of alignment with the top of the midnight hour but that still wouldn't quite work because then the question would be alignment with midnight on what day?  An every 7 minute frequency doesn't align with midnight on every day as the number of minutes in a day is not evenly divisible by 7.  The same sort of problem would occur with an every 5 hours frequency.

I suppose you could document that only frequencies that are an evenly divisible fraction of 24 hours are allowed and throw an exception in other cases, requiring callers to fall back to the other form of the method where a start instant is specified to support the other cases but I wonder if it might be simpler to just take a cron-style string for the frequency argument instead of an int.  The cron-style expression gives you the additional information about alignment to the clock.  If you do this you don't necessarily need the other form of the method with the start instant parameter.  The cron-style frequency would get rid of support for some odd things like the true every 7 minute scenario but I don't think those are really necessary.  It also gets rid of the need to resort to specifying a start instant for frequencies longer than 24 hours.

The overloaded withView() that infers the frequency would certainly make sense for output views.  It may be applicable often enough to be useful for input views as well I guess.

I wonder a bit whether it would make sense to have an input vs output designation in the withView method signature.  With that for output views we could remove the confusing need (or possibility) to ever specify a frequency.

**Comment by ben-roling** [comment]
Something I guess you have to be careful about with all the cron-style stuff is that it looks like you can express a coordinator frequency in the cron expression style but it does not appear to me on the surface that you can express a dataset frequency in that same fashion.  You would have to do conversion of the cron-style expression to the (initial-instance, frequency) pair and could only really support cron expressions that can be cleanly converted.

So, for example, you might wish to throw an exception when a job is scheduled with a cron expression that can't be converted to the other style.  For example, a first day of the month or last day of the month frequency wouldn't really work since you couldn't declare a dataset with such a frequency.

**Comment by rbrush** [comment]
I like the idea of cron-based frequencies across the board.  As you point out we would have to convert them to frequency and initial instance ourselves and not everything translates. However, pretty much every reasonable cron schedule I could envision would...and documenting and throwing an exception for unsupported frequencies seems acceptable. 

So I'm leaning towards this now:
- Drop ScheduleBuilder.withView as it exists today.
- Add scheduleBuilder.withInput(String name, String uriTemplate, String cronFrequency)
- Add scheduleBuilder.withOutput(String name, String uriTemplate), which uses the frequency of the schedule itself.

That seems concise to me, and it also makes it clear what the schedule expects for inputs and outputs.

(Side note:  it might be worth pushing cron support for <datain> upstream into Oozie itself...so our conversion would be a temporary state. Oozie is inconsistent between its cron and legacy-style frequencies now so it seems like that's where the root of the issue should be handled.)

**Comment by ben-roling** [comment]
I think your ScheduleBuilder proposal looks reasonable.  If we can stick to cron-based schedules across the board it does seem simpler.

With regard to pushing support for cron schedules on dataset definitions to Oozie -- yeah, it seems reasonable to suggest that.

**Comment by rbrush** [comment]
The proposal is implemented in the above commit. Local tests are working. I'm going to verify this running on a cluster before merging to master.

I also tracked down an Oozie issue to get cron-style frequencies for data availability. It seems like they are open to this change now that people are asking for it:

https://issues.apache.org/jira/browse/OOZIE-1431

**Comment by rbrush** [comment]
Alright, the above commit does the trick and is working on a cluster. I'm going to go ahead and close this issue. We can reopen or open another one if I'm missing something.
