### ISSUE TITLE
Re-installing an app to same target directory behaves strangely

### ISSUE THREAD

**Issue by ben-roling** [rbrush/kite-apps#6]
Running two install commands targeted to the same directory results in the directory containing a mix of files from the first and second version of the application.  Where the two versions contain files with the same path, the newer version wins but the any files from the first version that are not included in the 2nd version remain.

If nothing else, all the files from the 1st version should be removed before the 2nd version is installed.  More broadly I think re-install should be made more intentional such that if there are already files in the target directory the install fails unless there is something on the command line indicating it should be forced.

Perhaps this falls into a broader issue of expanding the set of CLI commands that can be invoked to add "update" and "delete" commands to update and remove apps.

**Comment by rbrush** [comment]
Yes, this is a use case I hadn't gotten to yet. ;) I agree with the idea of preventing re-installation to a specified location unless forced, since removing old artifacts could impact running jobs. We should also make file installation atomic by writing to a temporary location and renaming the directory.

**Comment by rbrush** [comment]
For now I'm just going to prohibit installation to a location that already exists. We generally want to encourage patterns of landing new installations in a new place, e.g. release1 might look like this:

``` bash
kite-apps install example-app-1.0.0.jar org.example.ExampleApp /user/me/release1/example
```

... and a subsequent installation would be like this:

``` bash
kite-apps install example-app-1.0.0.jar org.example.ExampleApp /user/me/release2/example
```

After which the first one can be removed. Support to shut down running bundles and removing the release1 after release2 has been verified seems useful, so I logged issue #10 to track that.

**Comment by ben-roling** [comment]
Sounds good enough to me.

**Comment by rbrush** [comment]
Fixed in the above commit and tested on a VM. I had to fix a few places that had absolute paths and make them relative, so this required some internal refactoring, but eliminating those made the end state cleaner anyway.
